### ISSUE TITLE
running an entire test class throws error

### ISSUE THREAD

**Issue by julesx** [daishi4u/ForceCode#51] opened 2018-08-22 13:08 UTC
this happens when i try to run an entire test class by hovering over @isTest and clicking the tooltip

![image](https://user-images.githubusercontent.com/3010047/44465155-befd4600-a5ea-11e8-9269-537700c1a240.png)

there are only two test methods in it and i am able to successfully run each one individually

**Comment by daishi4u** [comment] 2018-08-22 16:56
I have seen this, but I can't consistently get it to reproduce, but I'll get it fixed by the next release.

**Comment by daishi4u** [comment] 2018-08-23 03:38
Got it fixed in 3.7.1. Was due to the way I was parsing text files to get the method names and to tell if a person was wanting to run the whole class or not.

**Closed by daishi4u** 2018-08-23 03:38 UTC
