### ISSUE TITLE
Saving/deploying apex classes not happening

### ISSUE THREAD

**Issue by ennoucas** [daishi4u/ForceCode#36] opened 2018-07-30 18:55 UTC
When I try to deploy an apex class, I see that force code runs the saving method but it don't deploy anything to Salesforce nor generate any error. I am logged in. Version 3.5.10.
Thanks

**Comment by ennoucas** [comment] 2018-07-30 18:58
Randomly happening. I've deleting all the apex classes and the wsMembers file. I've downloaded the apex classes back again (with Open File) and now I can save it..

**Comment by julesx** [comment] 2018-07-30 20:51
I also am having this issue.  I am NOT using the ForceCode Open File.

There is no error, everything seems to be happening as it was, but the file is not saved on my org.

**Comment by daishi4u** [comment] 2018-07-31 00:11
Did either of you try going back to 3.5.9? Trying to narrow down the version that last worked...

**Comment by daishi4u** [comment] 2018-07-31 12:43
Found the cause of this and it should be fixed in 3.5.11. The issue was only in 3.5.10. Let me know if you face any other issues related to this. I am going on vacation and won't be working on the plugin till probably Saturday, but can still respond to issues, just won't be able to work on them. Thanks!

**Comment by julesx** [comment] 2018-08-01 13:27
seems to be working nicely once again

**Closed** 2018-08-03 23:32 UTC
