### ISSUE TITLE
[BUG] Error messages not fetched anymore

### ISSUE THREAD

**Issue by Bartheleway** [daishi4u/ForceCode#38] opened 2018-08-03 11:25 UTC
Hi,

I don't remember in which version this was working (probably 3.5.8) but when I was saving a class and that this save was not working (because of bad code), I used to have the list of errors added to the "problems" list of my file.

This doesn't work anymore so it's really hard to know why the save failed.

**Comment by raghurankawat** [comment] 2018-08-03 14:23
Yes, facing the same issue, Can't see the cause anymore.

**Comment by hwong103** [comment] 2018-08-03 22:21
Like to say I experienced this issue yesterday. At times I had to open up Dev console to figure out what was wrong.

I believe the error that appears in the extension is just a notification that says Syntax Error but nothing appears in the problems panel

**Comment by daishi4u** [comment] 2018-08-03 23:33
I have left the error reporting in the problems panel to the salesforce apex language extension with this release, as ForceCode only produces duplicates, so this isn't a bug.

**Comment by Bartheleway** [comment] 2018-08-04 09:31
@daishi4u the apex language extension only give us simple error message like @raghurankawat said. These messages are usefull but doesn't cover all possible issues that we might have. The checks happening while saving on Salesforce give us more error messages. I think people don't mind having duplicates instead of having not all the error messages.

Maybe we can define a set of error messages given by the apex language extension and use it to filter the error messages displayed by forceCode ?

**Comment by jmfierroh** [comment] 2018-08-07 08:17
@Bartheleway the language extension only gives me (basic) syntax errors, like not writing a complete method signature. But really basic things like a missing return or a missing comma in a query are not reported, and I have to wait until after compiling to the server to find those out. (My orgs are the old-style orgs, not a SF-DX org, if that helps explain my situation)

**Comment by daishi4u** [comment] 2018-08-08 02:07
I only use the old style orgs as well, but anyways this is fixed in v3.5.12.

**Closed** 2018-08-08 23:00 UTC
Labels: bug
